name = input("Enter your name: ")
age = int(input("Enter your age: "))
weight = int(input("Enter your weight: "))
height = int(input("Enter your height: "))
favorite_sport = input("Enter your favorite sport: ")
dream_job = input("Enter your dream job: ")

print("------- MY PROFILE -------")
print(" ")
print("Name:", name)
print("Age:", age)
print("Weight:", weight, "kg")
print("Height :", height, "cm")
print("Height:", height)
print("Favorite sport:", favorite_sport)
print("Dream job:", dream_job)
print(" ")
print("---------------------------")