name = input("Enter your name: ")
clas = input("Enter your class: ")
school = input("Enter your school: ")
district = input("Enter your district: ")
favorite_subject = input("Enter your favorite subject: ")

print("===================")
print("STUDENT CARD")
print("===================")
print("Name:             ", name)
print("Class:            ", clas)
print("School:           ", school)
print("District:         ", district)
print("Favorite subject: ", favorite_subject)
print("===================")
